# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/venv/Scripts" # Location of package manifests
    schedule:
      interval: "daily"
allow:
      # Allow updates for Flask
      - dependency-name: "flask"
      # Allow updates for CS50 
      - dependency-name: "cs50"     
      # Allow updates for Requests 
      - dependency-name: "requests" 
      
